name: Vagrant Vmware box publish

on:
  push:
  schedule:
    - cron: "1 1 * * 1"

jobs:
  box_build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      - name: Setup HashiCorp Vagrant
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt install -y vagrant
      - name: Setup Vmware
        run: |
          export VMWARE_VERSION=17.6.0
          export VMWARE_BUILD=24238078
          export VAGRANT_VMWARE_UTILITY_VERSION=1.0.23
          sudo apt-get update
          sudo apt-get install -y software-properties-common wget 
          wget -q https://softwareupdate.vmware.com/cds/vmw-desktop/ws/${VMWARE_VERSION}/${VMWARE_BUILD}/linux/core/VMware-Workstation-${VMWARE_VERSION}-${VMWARE_BUILD}.x86_64.bundle.tar
          tar xf VMware-Workstation-${VMWARE_VERSION}-${VMWARE_BUILD}.x86_64.bundle.tar
          sudo bash VMware-Workstation-${VMWARE_VERSION}-${VMWARE_BUILD}.x86_64.bundle --console --eulas-agreed --required --set-setting vmware-workstation serialNumber "" --set-setting vmware-player serialNumber "" 
          wget -q https://releases.hashicorp.com/vagrant-vmware-utility/${VAGRANT_VMWARE_UTILITY_VERSION}/vagrant-vmware-utility_${VAGRANT_VMWARE_UTILITY_VERSION}-1_amd64.deb
          sudo dpkg -i vagrant-vmware-utility_${VAGRANT_VMWARE_UTILITY_VERSION}-1_amd64.deb
          sudo systemctl restart vagrant-vmware-utility
          vagrant --version
          packer --version
          vmware --version
      - name: Build box artifact
        run: |
          export PACKER_LOG=1
          make build-vmware
      - name: Upload build artifact
        env:
          VAGRANT_TOKEN: ${{ secrets.VAGRANT_TOKEN }}
        if: github.ref  == 'refs/heads/main'
        run: |
          export VERSION="$(date +%Y%m%d).${{github.run_number}}.${{github.run_attempt}}"
          export PROVIDER="vmware_desktop"
          export BOX_PATH="./centos9stream.box"
          make upload
